using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.WebSockets;
using System.Text;
using System.Threading.Tasks;

namespace CodeChallenge1
{
    internal class CodeChallenge2
    {

        //Fibonacci Even Sum 
        //Each new term in the Fibonacci sequence is generated by adding the pervious two terms. By starting with q and w, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


        private static void Main(string[] args)
        {

            var q = 0;
            var w = 1;
            var sum = 0;

            for (int i = 3; i < 10; i++)
            {
                sum = q + w;
               Console.WriteLine($"{q} + {w} = {sum}");
                Console.WriteLine("-------------------");
                q = w;
                w = sum;
                

            }




        }//end main()

       
        

    }//end class
}//end namespace
